### ISSUE TITLE
TypeScript compiler fails with examples

### ISSUE THREAD

**Issue by liamness** [looker-open-source/extension-examples#48]
Running `yarn tsc --noEmit` inside the "hello world" and "kitchen sink" examples results in errors. As such, I am not sure how these examples can be used as a robust jumping off point for TypeScript-based Looker extension development.

I see that TypeScript is not actually used to build the projects, but instead Webpack and Babel are preferred. I agree with this choice as it is more flexible, given TypeScript does not support plugins in the same way Babel does. However you still need a way to run type checking via the command line, so that the correctness of the project can be assured during local development or CI runs.

**Comment by bryans99** [comment]
Fixed
